# @package _global_
# This referes to Vanilla Styled 4dvarnet with  periodic BCs in convs. It has observation noise of 0.04

paths:
    l96: /Odyssey/public/l96_dataset/L96_truth_obs_mask_boc2010.nc

domain: ???

trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  logger: 
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: ''
  max_epochs: 50
  callbacks:
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_mse
      save_top_k: 3
      filename: '{val_mse:.5f}-{epoch:03d}'

datamodule:
  _target_: contrib.L96.data.BaseDataModule
  input_da: 
    _target_: contrib.L96.utils.load_l96_data #src.utils.load_altimetry_data   # 
    path:  ${paths.l96} # ${paths.natl_gf_5nads}
  domains:
    train:
      time: {_target_: builtins.slice, _args_: [15200, 40000]}
    val: 
      time: {_target_: builtins.slice, _args_: [9200, 15000]}
    test: 
      time: {_target_: builtins.slice,  _args_: [500, 9000]}
  xrds_kw:
    patch_dims: { time: 200, lat: 40, lon: 1}
    strides: { time: 20, lat: 40, lon: 1}
    domain_limits: ${domain.train}
  dl_kw: {batch_size: 32, num_workers: 1}
  aug_kw:
    aug_factor: 2
    aug_only: True
    noise_sigma: 0.03

model:
  _target_: contrib.L96.models.LitUnet_like_4dVarNet
  persist_rw: False
  opt_fn:
    _target_: ocean4dvarnet.utils.cosanneal_lr_adam
    _partial_: true
    lr: 1e-3
    T_max: ${trainer.max_epochs}
  rec_weight:
      _target_: contrib.L96.utils.get_triang_time_wei
      patch_dims: ${datamodule.xrds_kw.patch_dims}
      crop: {time: 0, lat: 0, lon: 0}
      offset: 0
  solver: 
    _target_: contrib.QG.models.UNet_periodic_withInput
    n_channels: 20  # n_channels = n_obs_channels + n_init_channels
    n_classes: 10
    bilinear: True
    block:
      _target_: contrib.QG.utils.ResBlock_periodic
      _partial_: True
    add_input: False
    #channel_dims: [32,64,128,256,512]
      
       
  test_metrics: ${metrics.test_metrics}
  pre_metric_fn: 
        _target_: xarray.Dataset.sel
        _partial_: True
        time: {_target_: builtins.slice, _args_: [500, 9000]}
        lat: ${domain.test.lat}
        lon: ${domain.test.lon}

metrics:
  nrmse_scores: {_target_: ocean4dvarnet.utils.rmse_based_scores_from_ds, _partial_: True}
  psd_scores: {_target_: ocean4dvarnet.utils.psd_based_scores_from_ds, _partial_: True}
  get0: {_target_: operator.itemgetter, _args_: [0]}
  get1: {_target_: operator.itemgetter, _args_: [1]}
  test_metrics:
    'mu': {_target_: ocean4dvarnet.utils.pipe, _partial_: true, fns: ['${metrics.nrmse_scores}', '${metrics.get0}']}
    'sig': {_target_: ocean4dvarnet.utils.pipe, _partial_: true, fns: ['${metrics.nrmse_scores}', '${metrics.get1}']}
    'lx': {_target_: ocean4dvarnet.utils.pipe, _partial_: true, fns: ['${metrics.psd_scores}', '${metrics.get0}']}
    'lt': {_target_: ocean4dvarnet.utils.pipe, _partial_: true, fns: ['${metrics.psd_scores}', '${metrics.get1}']}

entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: ocean4dvarnet.train.base_training
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}

defaults:
  - /domain: l96_sim_40
  - _self_

